ASPLearning/ViewModels/VideoViewModel.cs
using ASPLearning.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Web;

namespace ASPLearning.ViewModels
{
   public class VideoViewModel : VideoDto
   {
      public CourseDto Course { get; set; }
      public UserDto Teacher { get; set; }
      public bool IsWatched { get; set; }
      public VideoViewModel() : base()
      {
         Course = new CourseDto();
         Teacher = new UserDto();
         IsWatched = false;
      }
      public VideoViewModel(DataRow dr) : base(dr)
      {
         Course = new CourseDto();
         Teacher = new UserDto();
         IsWatched = false;
      }
      public VideoViewModel(VideoDto video)
      {
         foreach (PropertyInfo prop in video.GetType().GetProperties())
         {
            PropertyInfo prop2 = video.GetType().GetProperty(prop.Name);
            prop2.SetValue(this, prop.GetValue(video, null), null);
         }
         Course = new CourseDto();
         Teacher = new UserDto();
         IsWatched = false;
      }
   }
}

ASPLearning/Controllers/PostCourseController.cs
using ASPLearning.DAO;
using ASPLearning.Models;
using ASPLearning.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPLearning.Controllers
{
   public class PostCourseController : Controller
   {
      //
      // GET: /PostCourse/
      public ActionResult Index()
      {
         if (Session["username"] == null || TypeUtils.Parse.ToInt(Session["usertype"]) != 2)
            return Redirect("/");

         List<CategoryDto> ListCategories = CategoryDao.Gets();
         ViewBag.ListCategories = ListCategories;
         //setCatViewBag();
         return View();
      }
      public ActionResult Video()
      {
         if (Session["username"] == null || TypeUtils.Parse.ToInt(Session["usertype"]) != 2)
            return Redirect("/");
         int teacher = TypeUtils.Parse.ToInt(Session["user_id"]);
         List<CourseDto> listCourse = CourseDao.GetByTeacher(teacher);
         ViewBag.listCourse = listCourse;
         return View();
      }
      [HttpPost]
      public ActionResult PostVideo(VideoDto dto)
      {
         dto.CreatedDate = DateTime.Now;
         dto.UpdatedDate = DateTime.Now;
         dto.OwnerId = Convert.ToInt32(Session["user_id"]);
         int result = VideoDao.insert(dto);
         if (result != -1)
         {
            return Redirect("/Dashboard#courses");
         }
         else
         {
            Session["error_postcourse"] = "Post Course: Fail to post your course. Please check your some infomations and try again!";
            return View("Video", dto);
         }
      }
      [HttpPost]
      public ActionResult Post(CourseDto dto)
      {
         dto.CreatedTime = DateTime.Now;
         dto.IsApproved = false;
         dto.TeacherId = Convert.ToInt32(Session["user_id"]);
         int result = 0;
         if (!CourseDao.isExists(dto))
            result = CourseDao.insert(dto);
         if (result != -1)
         {
            return Redirect("/Dashboard#courses");
         }
         else
         {
            Session["error_postcourse"] = "Post Course: Fail to post your course. Please check your some infomations and try again!";
            return View("index", dto);
         }
      }

      public void setCatViewBag(long? selectedID = null)
      {
         ViewBag.CategoryID = new SelectList(CategoryDao.Gets(), "Id", "name", selectedID);
      }
   }
}

ASPLearning/Views/PostCourse/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Header.cshtml";
}
@model ASPLearning.Models.CourseDto

<h4 class="text-center mt-4">Post Course</h4>
<div class="d-flex justify-content-center">
    @using (Html.BeginForm("Post", "PostCourse", FormMethod.Post))
    {
        <form>
            <div class="form-group">
                @Html.LabelFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Course name", @autofocus = "autofocus", @required = "required" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.Fee)
                    @Html.TextBoxFor(model => model.Fee, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.CategoryId)
                    @Html.DropDownListFor(model => model.CategoryId, new System.Web.Mvc.SelectList(ViewBag.ListCategories, "Id", "name"), new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(model => model.CategoryId)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IntroVideoLink)
                @Html.TextBoxFor(model => model.IntroVideoLink, new { @class = "form-control", @required = "required" })
                @Html.ValidationMessageFor(model => model.IntroVideoLink)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description)
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @required = "required" })
                @Html.ValidationMessageFor(model => model.Description)
            </div>

            <div class=" d-flex justify-content-center mt-3 mb-5"><button type="submit" class="btn btn-primary">Post</button></div>
        </form>
    }
</div>

ASPLearning/Views/PostCourse/Video.cshtml
@{
    Layout = "~/Views/Shared/_Header.cshtml";
}
@model ASPLearning.Models.VideoDto

<h4 class="text-center mt-4">Post Course</h4>
<div class="d-flex justify-content-center">
    @using (Html.BeginForm("PostVideo", "PostCourse", FormMethod.Post))
    {
        <form>
            <div class="form-group">
                @Html.LabelFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Video name", @autofocus = "autofocus", @required = "required" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.CourseId)
                    @Html.DropDownListFor(model => model.CourseId, new System.Web.Mvc.SelectList(ViewBag.listCourse, "Id", "Name"), new { @class = "form-control", @required = "required", @style="width: 100%" })
                    @Html.ValidationMessageFor(model => model.CourseId)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VideoLink)
                @Html.TextBoxFor(model => model.VideoLink, new { @class = "form-control", @required = "required" })
                @Html.ValidationMessageFor(model => model.VideoLink)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description)
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @required = "required" })
                @Html.ValidationMessageFor(model => model.Description)
            </div>

            <div class=" d-flex justify-content-center mt-3 mb-5"><button type="submit" class="btn btn-primary">Post</button></div>
        </form>
    }
</div>

ASPLearning/Views/PostCourse/success.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Header.cshtml";
}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <h3>Success!</h3>
</body>
</html>