ASPLearning/ViewModels/ManagementViewModel.cs
using ASPLearning.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASPLearning.ViewModels
{
   public class ManagementViewModel
   {
      public List<UserDto> ListTeachers { get; set; }
      public List<CourseManagerViewModel> ListCourses { get; set; }
      public List<VideoViewModel> ListVideos { get; set; }
      public ManagementViewModel()
      {
         ListTeachers = new List<UserDto>();
         ListCourses = new List<CourseManagerViewModel>();
         ListVideos = new List<VideoViewModel>();
      }
   }
}

ASPLearning/Controllers/ManagementController.cs
using ASPLearning.DAO;
using ASPLearning.Models;
using ASPLearning.Utils;
using ASPLearning.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPLearning.Controllers
{
   public class ManagementController : Controller
   {
      // GET: Management
      public ActionResult Index()
      {
         if (Session["username"] == null)
            return RedirectToAction("Index","Login");
         if (TypeUtils.Parse.ToInt(Session["usertype"]) != 0)
            return RedirectToAction("Index", "Home");
         //
         ManagementViewModel model = new ManagementViewModel();
         model.ListTeachers = UserDao.GetAllTeacher().OrderByDescending(n => n.IsActive).ToList();
         model.ListCourses = CourseDao.GetListViewManagement();
         foreach (var course in model.ListCourses)
         {
            var list = VideoDao.GetByCourseId(course.Id).Select(n => new VideoViewModel(n)).ToList();
            model.ListVideos.AddRange(list);
         }
         var unAssignedVideos = VideoDao.GetByCourseId(0);
         if (unAssignedVideos.Count != 0)
         {
            foreach (var video in unAssignedVideos)
               model.ListVideos.Add(new VideoViewModel(video));
         }
         foreach (var video in model.ListVideos)
         {
            var course = model.ListCourses.FirstOrDefault(n => n.Id == video.CourseId);
            if (course == null)
               video.Course = new CourseDto() { Name = "Unknown" };
            else
               video.Course = new CourseDto() { Name = course.Name, Id = course.Id, IsApproved = course.IsApproved};
            var teacher = model.ListTeachers.FirstOrDefault(n => n.UserId == video.OwnerId);
            if (teacher == null)
               video.Teacher = new UserDto() { FirstName = "Unknown", LastName = "" };
            else
               video.Teacher = teacher;
         }
         return View(model);
      }
      [HttpPost]
      public ActionResult UnApprove(string id)
      {
         CourseDao.UpdateApprove(TypeUtils.Parse.ToInt(id), false);
         return Redirect("/Management#courses");
      }
      [HttpPost]
      public ActionResult Approve(string id)
      {
         CourseDao.UpdateApprove(TypeUtils.Parse.ToInt(id), true);
         return Redirect("/Management#courses");
      }
      [HttpPost]
      public ActionResult UnConfirm(string id)
      {
         UserDao.updateStatus(TypeUtils.Parse.ToInt(id), false);
         return Redirect("/Management#users");
      }
      [HttpPost]
      public ActionResult Confirm(string id)
      {
         UserDao.updateStatus(TypeUtils.Parse.ToInt(id), true);
         return Redirect("/Management#users");
      }
   }
}

ASPLearning/Views/Management/Index.cshtml
@{
   Layout = "~/Views/Shared/_Header.cshtml";
}
@model ASPLearning.ViewModels.ManagementViewModel
<style>
   table.dataTable thead .sorting:after,
   table.dataTable thead .sorting:before,
   table.dataTable thead .sorting_asc:after,
   table.dataTable thead .sorting_asc:before,
   table.dataTable thead .sorting_asc_disabled:after,
   table.dataTable thead .sorting_asc_disabled:before,
   table.dataTable thead .sorting_desc:after,
   table.dataTable thead .sorting_desc:before,
   table.dataTable thead .sorting_desc_disabled:after,
   table.dataTable thead .sorting_desc_disabled:before {
      bottom: .5em;
   }
</style>
<link href="~/Content/mdbcss/addons/datatables.min.css" rel="stylesheet">
<div class="row">
   <div class="col-2" id="dashboardTab">
      <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
         <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#users" role="tab" aria-controls="v-pills-home" aria-selected="true">User Management</a>
         <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#courses" role="tab" aria-controls="v-pills-profile" aria-selected="false">Course Management</a>
         <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#videos" role="tab" aria-controls="v-pills-profile" aria-selected="false">Video Management</a>
      </div>
   </div>
   <div class="col-10">
      <!--Users-->
      <div class="tab-content" id="v-pills-tabContent">
         <div class="tab-pane fade show active" id="users" role="tabpanel" aria-labelledby="v-pills-home-tab">
            <div style="padding-left: 50px; padding-right: 50px;">
               <br />
               <h1>List of Teachers</h1>
               <table class="table" id="my_users" cellspacing="0" width="100%">
                  <thead class="thead-light">
                     <tr>
                        <th scope="col">User ID</th>
                        <th scope="col">Firstname</th>
                        <th scope="col">Lastname</th>
                        <th scope="col">Birthday</th>
                        <th scope="col">Is Actice</th>
                        <th scope="col">Action</th>
                     </tr>
                  </thead>
                  <tbody>
                     @if (Model.ListTeachers.Count == 0)
                     {
                        <tr>
                           <td colspan="5" class="text-center">Nothing to display</td>
                        </tr>
                     }
                     @foreach (var dto in Model.ListTeachers)
                     {
                        <tr>
                           <th scope="row">@dto.UserId</th>
                           <td>@dto.FirstName</td>
                           <td>@dto.LastName</td>
                           <td>@dto.DOB</td>
                           @if (dto.IsActive == true)
                           {
                              <td><span class="badge badge-success">Active</span></td>
                           }
                           else
                           {
                              <td><span class="badge badge-secondary">Inactive</span></td>
                           }
                        <td style="white-space: nowrap">
                           <div class="btn-group" role="group" aria-label="First group">
                              <a class="btn btn-outline-primary" href="/Teacher?id=@dto.UserId">
                                 <i class="fa fa-eye" aria-hidden="true"></i>
                              </a>
                              @if (dto.IsActive == true)
                              {
                                 using (Html.BeginForm("UnConfirm", "Management", new { id = @dto.UserId }, FormMethod.Post))
                                 {
                                    <button class="btn btn-outline-danger" type="submit">
                                       <i class="fa fa-times" aria-hidden="true"></i>
                                    </button>
                                 }
                              }
                              else
                              {
                                 using (Html.BeginForm("Confirm", "Management", new { id = @dto.UserId }, FormMethod.Post))
                                 {
                                    <button class="btn btn-outline-success" type="submit">
                                       <i class="fa fa-check" aria-hidden="true"></i>
                                    </button>
                                 }
                              }
                           </div>
                        </td>
                        </tr>
                     }

                  </tbody>
               </table>
            </div>
         </div>
         <!--Users End-->
         <!--Courses-->
         <div class="tab-pane fade" id="courses" role="tabpanel" aria-labelledby="v-pills-profile-tab">
            <div style="padding-left: 50px; padding-right: 50px;">
               <br />
               <h1>List of courses</h1>
               <table class="table" id="my_courses">
                  <thead class="thead-light">
                     <tr>
                        <th scope="col">#</th>
                        <th scope="col">Course Name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Teacher</th>
                        <th scope="col">Created Time</th>
                        <th scope="col">Action</th>
                     </tr>
                  </thead>
                  <tbody>
                     @if (Model.ListCourses.Count == 0)
                     {
                        <tr>
                           <td colspan="7" class="text-center">Nothing to display</td>
                        </tr>
                     }
                     @foreach (var course in Model.ListCourses)
                     {
                        <tr>
                           <th scope="row">@course.Order</th>
                           <td>
                              @course.Name
                              @if (course.IsApproved == false)
                              {
                                 <span class="badge badge-secondary">Inactive</span>
                              }
                           </td>
                           <td>@course.Category</td>
                           <td>@course.Teacher</td>
                           <td>@course.CreatedTime</td>
                           <td style='white-space: nowrap'>
                              <div class="btn-group" role="group" aria-label="First group">
                                 <a class="btn btn-outline-primary" href="/Courses?id=@course.Id">
                                    <i class="fa fa-eye" aria-hidden="true"></i>
                                 </a>
                                 @if (course.IsApproved)
                                 {
                                    using (Html.BeginForm("UnApprove", "Management", new { id = @course.Id }, FormMethod.Post))
                                    {
                                       <button class="btn btn-outline-danger" type="submit">
                                          <i class="fa fa-times" aria-hidden="true"></i>
                                       </button>
                                    }
                                 }
                                 else
                                 {
                                    using (Html.BeginForm("Approve", "Management", new { id = @course.Id }, FormMethod.Post))
                                    {
                                       <button class="btn btn-outline-success" type="submit">
                                          <i class="fa fa-check" aria-hidden="true"></i>
                                       </button>
                                    }
                                 }
                              </div>


                           </td>
                        </tr>
                     }
                  </tbody>
               </table>
            </div>
         </div>
         <!--Courses End-->
         <!--Videos-->
         <div class="tab-pane fade" id="videos" role="tabpanel" aria-labelledby="v-pills-profile-tab">
            <div style="padding-left: 50px; padding-right: 50px;">
               <div id="accordion">
                  <table class="table" id="my_videos">
                     <thead class="thead-light">
                        <tr>
                           <th scope="col">#</th>
                           <th scope="col">Video Name</th>
                           <th scope="col">Course Name</th>
                           <th scope="col">Teacher</th>
                           <th scope="col">Updated Date</th>
                           <th scope="col">Action</th>
                        </tr>
                     </thead>
                     <tbody>
                        @foreach (var video in Model.ListVideos)
                        {
                           <tr>
                              <th scope="row">@video.Id</th>
                              <td>@video.Name</td>
                              <td>
                                 @video.Course.Name
                                 @if (video.Course.IsApproved == false)
                                 {
                                    <span class="badge badge-secondary">Inactive</span>
                                 }
                              </td>
                              <td>@video.Teacher.FirstName @video.Teacher.LastName</td>
                              <td>@video.UpdatedDate.ToString("MM/dd/yyyy")</td>
                              <th>
                                 <a class="btn btn-outline-primary" href="/Courses/Video?id=@video.Id">
                                    <i class="fa fa-eye" aria-hidden="true"></i>
                                 </a>
                              </th>
                           </tr>
                        }
                     </tbody>
                  </table>
               </div>
            </div>
         </div>
         <!--Videos End-->
      </div>
      </div>
   </div>
<script>
   function DashboardOnLoad() {
      const url = document.location.href;
      if (url.includes('#')) {
         var activeTab = url.substring(url.indexOf("#") + 1);
         $('a[href="#' + activeTab + '"]').tab('show')
      }
   }
   window.addEventListener('DOMContentLoaded', (event) => {
      const url = document.location.href;
      if (url.includes('#')) {
         var activeTab = url.substring(url.indexOf("#") + 1);
         $('a[href="#' + activeTab + '"]').tab('show')
      }
      console.log('DOM fully loaded and parsed');
   });
      $(document).ready(function () {
         $('#my_videos').DataTable();
      $('.dataTables_length').addClass('bs-select');
      });
         $(document).ready(function () {
         $('#my_users').DataTable();
      $('.dataTables_length').addClass('bs-select');
   });
   $(document).ready(function () {
      $('#my_courses').DataTable();
      $('.dataTables_length').addClass('bs-select');
   });
</script>
<script type="text/javascript" src="~/Scripts/mdbjs/addons/datatables.min.js"></script>