ASPLearning/ViewModels/VideoViewModel.cs
using ASPLearning.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Web;

namespace ASPLearning.ViewModels
{
   public class VideoViewModel : VideoDto
   {
      public CourseDto Course { get; set; }
      public UserDto Teacher { get; set; }
      public bool IsWatched { get; set; }
      public VideoViewModel() : base()
      {
         Course = new CourseDto();
         Teacher = new UserDto();
         IsWatched = false;
      }
      public VideoViewModel(DataRow dr) : base(dr)
      {
         Course = new CourseDto();
         Teacher = new UserDto();
         IsWatched = false;
      }
      public VideoViewModel(VideoDto video)
      {
         foreach (PropertyInfo prop in video.GetType().GetProperties())
         {
            PropertyInfo prop2 = video.GetType().GetProperty(prop.Name);
            prop2.SetValue(this, prop.GetValue(video, null), null);
         }
         Course = new CourseDto();
         Teacher = new UserDto();
         IsWatched = false;
      }
   }
}

ASPLearning/Controllers/CoursesController.cs
using ASPLearning.DAO;
using ASPLearning.Models;
using ASPLearning.Utils;
using ASPLearning.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.HtmlControls;
namespace ASPLearning.Controllers
{
   public class CoursesController : Controller
   {
      // GET: Courses
      public ActionResult Index(string id)
      {
         CourseDto course = CourseDao.getById(Convert.ToInt32(id));
         if (course == null)
            return RedirectToAction("Index", "Home");

         CourseViewModel courseView = new CourseViewModel(course);
         courseView.ListVideos = VideoDao.GetByCourseId(course.Id);
         if (Session["username"] != null)
         {
            string username = Convert.ToString(Session["username"]);
            UserDto user = UserDao.getByUserName(username);
            if (user.Type == 1 && !course.IsApproved)
            {
               return RedirectToAction("Index", "Home");
            }
            courseView.ListWatched = WatchDao.GetByUser(user.UserId, course.Id).Select(n => n.Video).ToList();
            PaymentDto payment = PaymentDao.GetByCourseAndUser(user.UserId, course.Id);
            if (payment != null)
               courseView.Applied = true;
            else
               courseView.Applied = false;
            //
            var teacher = UserDao.getById(course.TeacherId);
            int usertype = TypeUtils.Parse.ToInt(Session["usertype"]);
            if (usertype == 0 || (teacher != null && usertype == 2 && TypeUtils.Parse.ToString(Session["username"]).Equals(teacher.UserName)))
            {
               courseView.Applied = true;
            }
         }
         ViewBag.Title = course.Name;
         return View(courseView);
      }
      [HttpPost]
      public ActionResult ApplyCourse(string id)
      {
         int course_id = TypeUtils.Parse.ToInt(id);
         if (Session["username"] == null)
            return RedirectToAction("Index", "Login");
         CourseDto dto = CourseDao.getByCourseId(course_id);
         CourseManagerViewModel model = new CourseManagerViewModel()
         {
            Id = dto.Id,
            Name = dto.Name,
            Price = dto.Fee == 0 ? "Free" : "$" + dto.Fee.ToString()
         };
         model.Teacher = UserDao.getNameById(dto.TeacherId);
         model.Category = CategoryDao.GetNameById(dto.CategoryId);
         return View(model);
      }
      [HttpPost]
      public ActionResult Apply(string id)
      {
         int course_id = TypeUtils.Parse.ToInt(id);
         if (Session["username"] == null)
            return RedirectToAction("Index", "Login");
         //
         string username = Convert.ToString(Session["username"]);
         UserDto user = UserDao.getByUserName(username);
         PaymentDto payment = new PaymentDto();
         payment.User = user.UserId;
         payment.Course = course_id;
         payment.Type = Request.Form["exampleRadios"];
         payment.Amount = CourseDao.getPriceById(course_id);
         PaymentDao.Insert(payment);
         //
         return Redirect("/Courses?id=" + id); ;
      }
      public ActionResult Video(string id)
      {
         int VideoID = TypeUtils.Parse.ToInt(id);
         VideoDto video = VideoDao.GetById(VideoID);
         if (Session["username"] == null || video == null)
            return RedirectToAction("Index", "Home");
         
         VideoViewModel videoView = new VideoViewModel(video);
         videoView.Course = CourseDao.getById(video.CourseId);
         string username = Convert.ToString(Session["username"]);
         videoView.Teacher = UserDao.getByUserName(username);

         int UserId = TypeUtils.Parse.ToInt(Session["user_id"]);
         WatchDto watched = WatchDao.GetByVideoId(UserId, VideoID);
         videoView.IsWatched = (watched == null) ? false : true;
         //
         UserDto teacher = null;
         if (videoView.Course != null)
            teacher = UserDao.getById(videoView.Course.TeacherId);
         int usertype = TypeUtils.Parse.ToInt(Session["usertype"]);
         if (usertype == 0 || (teacher != null && usertype == 2 && TypeUtils.Parse.ToString(Session["username"]).Equals(teacher.UserName)))
         {
            videoView.IsWatched = true;
         }

         ViewBag.Title = video.Name;
         return View(videoView);
      }

      public ActionResult Register()
      {
         if (Session["username"] == null)
            return RedirectToAction("Index", "Home");
         UserDto dto = UserDao.getByUserName((string)Session["username"]); //Register (đang build)
         return View(dto);
      }
      [HttpPost]
      public ActionResult Complete()
      {
         int id = TypeUtils.Parse.ToInt(Request.Form["video_id"]);
         VideoDto video = VideoDao.GetById(id);
         if (Session["username"] == null || video == null)
            return RedirectToAction("Index", "Home");
         
         WatchDto dto = new WatchDto();
         dto.Course = video.CourseId;
         dto.Video = video.Id;
         dto.User = TypeUtils.Parse.ToInt(Session["user_id"]);
         WatchDao.Insert(dto);
         return Redirect("/Courses?id=" + video.CourseId); ;
      }
   }
}

ASPLearning/Views/Courses/ApplyCourse.cshtml
@{
   Layout = "~/Views/Shared/_Header.cshtml";
}
@model ASPLearning.ViewModels.CourseManagerViewModel
<link href="~/Content/css/pay.css" rel="stylesheet" />
<div class="container">
   <div class="row">
      <div class="col-xs-6 col-md-8">
         <div class="card">
            <div class="card-header">
               Do you want to apply this course?
            </div>
            <div class="card-body">
               Course name: @Model.Name<br />
               Category: @Model.Category <br />
               Teacher: @Model.Teacher<br />
            </div>
         </div>
      </div>
      <div class="col-xs-6 col-md-4">
         <div class="card">
            <div class="card-header">
               Bill
            </div>
            <div class="card-body" style="display: flex;">
               <div class="samelevel1">@Model.Name</div>
               <div class="samelevel2">
                  <b>@Model.Price</b>
               </div>


            </div>
            <div class="abc">
               <div class="samelevel1" style="font-weight: bold;">Total</div>
               <div class="samelevel2" style="color: red;">
                  @Model.Price
               </div>
            </div>
            @using (Html.BeginForm("Apply", "Courses", new { id = Model.Id }, FormMethod.Post))
            {
               if (!Model.Price.Equals("Free"))
               {
                  <hr />
                  <div class="form-group">
                     <div class="form-check form-inline">
                        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2"
                               value="1">
                        <img src="~/Content/picture/visa.jpg" width="20" height="15">
                        <label class="form-check-label" for="exampleRadios2">
                           Credit Card
                        </label>
                     </div><br>
                     <div class="form-check form-inline">
                        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2"
                               value="2" checked>
                        <img src="~/Content/picture/momo.png" width="20" height="15">
                        <label class="form-check-label" for="exampleRadios2">
                           MoMo
                        </label>
                     </div>
                     <br>
                     <div class="form-check form-inline">
                        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2"
                               value="3">
                        <img src="~/Content/picture/paypal.png" width="20" height="15">
                        <label class="form-check-label" for="exampleRadios2">
                           PayPal
                        </label>
                     </div>
                     <br>
                  </div>
               }

               <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                  Checkout
               </button>
            }
         </div>

      </div>
   </div>
</div>

ASPLearning/Views/Courses/Index.cshtml
@{
   Layout = "~/Views/Shared/_Header.cshtml";
}
@model ASPLearning.ViewModels.CourseViewModel

<div class="card">
   <div class="card-header">
      @Model.Name
   </div>
   <div class="card-body">
      <div class="row">
         <div class="col-md-8">
            <div class="embed-responsive embed-responsive-16by9 card">
               <iframe class="embed-responsive-item" src="@Model.IntroVideoLink"
                       allowfullscreen></iframe>
            </div>
         </div>

         <div class="col-md-4">
            @if (Model.Applied == false)
            {
               <div class="card">
                  <div class="card-body">
                     @if (Model.Fee == 0)
                     {
                        <h1 class="card-title pricing-card-title">Free</h1>
                     }
                     else
                     {
                        <h1 class="card-title pricing-card-title">$@Model.Fee</h1>
                     }

                     <ul style="margin-left: 0">
                        <li>
                           <i class="fa fa-clock-o" aria-hidden="true"></i> Thời lượng:04 giờ 22 phút

                        </li>
                        <li>
                           <i class="fa fa-play-circle" aria-hidden="true"></i> Giáo trình:32 bài giảng

                        </li>
                        <li><i class="fa fa-history" aria-hidden="true"></i> Sở hữu khóa học trọn đời</li>
                        <li><i class="fa fa-percent" aria-hidden="true"></i>Giảm thêm <b>10%</b> khi thanh toán online</li>
                     </ul>
                     @using (Html.BeginForm("ApplyCourse", "Courses", new { id = Model.Id } ,FormMethod.Post))
                     {
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                           Apply Now
                        </button>
                     }
                  </div>
               </div>
               <div class="card">
                  <div class="card-body">
                     <h3 class="card-title pricing-card-title">
                        Decription
                     </h3>
                     @Model.Description
                  </div>
               </div>
            }
            else
            {
               <div class="card border-0" id="videos">
                  <div class="list-group card-body">
                     <a class="list-group-item list-group-item-primary">List</a>
                     @foreach (var video in Model.ListVideos)
                     {
                        if (!Model.ListWatched.Contains(video.Id))
                        {
                           <a href="/Courses/Video?id=@video.Id" class="list-group-item list-group-item-action">@video.Name</a>
                        }
                        else
                        {
                           <a href="/Courses/Video?id=@video.Id" class="list-group-item list-group-item-action list-group-item-secondary">@video.Name</a>
                        }
                     }
                  </div>
               </div>
            }
         </div>
      </div>
      @if (Model.Applied == false)
      {
         <div class="row card border-0" id="videos">
            <div class="list-group card-body">
               <a class="list-group-item list-group-item-info">List</a>
               @foreach (var video in Model.ListVideos)
               {
                  <a href="#" class="list-group-item list-group-item-action">@video.Name</a>
               }
            </div>
         </div>
      }
   </div>
</div>

ASPLearning/Views/Courses/Register.cshtml
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Register</h2>

ASPLearning/Views/Courses/Video.cshtml
@{
   Layout = "~/Views/Shared/_Header.cshtml";
}
@model ASPLearning.ViewModels.VideoViewModel

<div class="card">
   <div class="card-header">
      <a href="/Course?id=@Model.Course.Id">@Model.Course.Name</a> - @Model.Name
   </div>
   <div class="card-body">
      <div class="row">
         <div class="col-md-8">
            <div class="embed-responsive embed-responsive-16by9 card">
               <iframe class="embed-responsive-item" src="@Model.VideoLink"
                       allowfullscreen></iframe>
            </div>
         </div>

         <div class="col-md-4">
            <div class="card">
               <div class="card-header">
                  @Model.Name
               </div>
               <div class="card-body">
                  <h3 class="card-title pricing-card-title">
                     Decription
                  </h3>
                  @Model.Description
                  <br />
                  @if (Model.IsWatched == false)
                  {
                     using (Html.BeginForm("Complete", "Courses", FormMethod.Post))
                     {
                        <input type="text" class="form-control" placeholder="Video_Id" autofocus="autofocus" name="video_id" id="input-text" value="@Model.Id" hidden />
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                           Complete
                        </button>
                     }
                  }
               </div>
            </div>

         </div>
      </div>
   </div>
</div>