ASPLearning/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASPLearning.DAO;
using ASPLearning.Models;
using ASPLearning.Utils;

namespace ASPLearning.Controllers
{
   public class LoginController : Controller
   {
      // GET: Login
      public ActionResult Index()
      {
         Session.Remove("error_login");
         Session.Remove("error_signup");
         if (Session["username"] != null )
         {
            return RedirectToAction("Index", "Home");
         }
         return View();
      }
      [HttpPost]
      public ActionResult AuthorizeMain()
      {
         Session.Remove("error_signup");
         var password = TypeUtils.Parse.ToString(Request.Form["pwd"]);
         var username = TypeUtils.Parse.ToString(Request.Form["username"]);
         var userData = UserDao.getByUserName(username);
         if (String.IsNullOrEmpty(username) || userData == null || !userData.Password.Equals(ConversionUtils.Users.Password(password)))
         {
            return RedirectToAction("Index", "Home");
         }
         else
         {
            Session.Remove("error_login");
            Session["username"] = userData.UserName;
            Session["usertype"] = userData.Type;
            Session["user_id"] = userData.UserId;
            return RedirectToAction("Index", "Home");
         }
      }
      [HttpPost]
      public ActionResult Authorize(UserDto userModel)
      {
         Session.Remove("error_signup");
         var pwd = ConversionUtils.Users.Password(userModel.Password);
         var userData = UserDao.getByUserName(userModel.UserName);
         if (userData == null || !userData.Password.Equals(pwd) || String.IsNullOrEmpty(userModel.UserName))
         {
            Session["error_login"] = "Sign in: Username or Password invalid!";
            return View("Index", userModel);
         }
         else
         {
            Session.Remove("error_login");
            Session["username"] = userData.UserName;
            Session["usertype"] = userData.Type;
            Session["user_id"] = userData.UserId;
            return RedirectToAction("Index", "Home");
         }
      }
      [HttpPost]
      public ActionResult SignUp(UserDto dto)
      {
         Session.Remove("error_login");
         var userData = UserDao.getByUserName(dto.UserName);
         if (String.IsNullOrEmpty(dto.UserName) || String.IsNullOrEmpty(dto.Password))
         {
            Session["error_signup"] = "Sign up: Username or Password invalid!";
            return View("index", dto);
         }
         else if (userData != null)
         {
            Session["error_signup"] = "Sign up: " + dto.UserName + " already exists!";
            return View("index", dto);
         }
         else
         {
            var retype = TypeUtils.Parse.ToString(Request.Form["retype_password"]);
            if (!retype.Equals(dto.Password))
            {
               Session["error_signup"] = "Sign up: Retype password incorrect! Please enter same password.";
               return View("index", dto);
            }
            var pwd = ConversionUtils.Users.Password(dto.Password);
            int type = TypeUtils.Parse.ToInt(Request.Form["usertype"]);
            dto.Password = pwd;
            if (type == 1)
               dto.IsActive = true;
            else
               dto.IsActive = false;
            dto.CreatedDate = DateTime.Now;
            dto.Type = type;
            var result = UserDao.insert(dto);
            if (result != -1)
            {
               Session.Remove("error_signup");
               Session["username"] = dto.UserName;
               Session["usertype"] = dto.Type;
               Session["user_id"] = userData.UserId;
               return RedirectToAction("Index", "Home");
            }
            else
            {
               Session["error_signup"] = "Sign up: Fail to sign up. Please try again!";
               return View("index", dto);
            }
         }
      }
      public ActionResult Logout()
      {
         Session.Abandon();
         return RedirectToAction("Index", "Home");
      }
   }
}

ASPLearning/Controllers/SearchController.cs
using ASPLearning.DAO;
using ASPLearning.Utils;
using ASPLearning.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPLearning.Controllers
{
   public class SearchController : Controller
   {
      // GET: Search
      public ActionResult Index()
      {
         SearchModel model = new SearchModel();
         int SearchType = TypeUtils.Parse.ToInt(Request.Form["search_type"]);
         string keyword = TypeUtils.Parse.ToString(Request.Form["search_value"]).Trim().ToLower();
         model.Keyword = keyword.ToUpper();
         if (SearchType == 0)
            return View();
         model.SearchType = SearchType;
         List<int> list_id = new List<int>();
         switch (SearchType)
         {
            case -1:
               model.ListCourse = CourseDao.GetsNotDeleted().FindAll(n => n.Name.ToLower().Contains(keyword) && n.IsApproved == true);
               model.ListCategory = CategoryDao.Gets().FindAll(n => n.Name.ToLower().Contains(keyword));
               model.ListTeacher = UserDao.GetAllTeacher().FindAll(n => n.FirstName.ToLower().Contains(keyword) || n.LastName.ToLower().Contains(keyword));
               break;
            case 1:
               model.ListCourse = CourseDao.GetsNotDeleted().FindAll(n => n.Name.ToLower().Contains(keyword) && n.IsApproved==true);
               break;
            case 2:
               model.ListCategory = CategoryDao.Gets().FindAll(n => n.Name.ToLower().Contains(keyword));
               list_id = model.ListCategory.Select(n => n.Id).ToList();
               model.ListCourse = CourseDao.GetsNotDeleted().FindAll(n => list_id.Contains(n.CategoryId) && n.IsApproved == true);
               break;
            case 3:
               model.ListTeacher = UserDao.GetAllTeacher().FindAll(n => n.FirstName.ToLower().Contains(keyword) || n.LastName.ToLower().Contains(keyword));
               list_id = model.ListTeacher.Select(n => n.UserId).ToList();
               model.ListCourse = CourseDao.GetsNotDeleted().FindAll(n => list_id.Contains(n.TeacherId) && n.IsApproved == true);
               break;
            default:
               model.ErrorMessage = "Search type not match!";
               break;
         }
         return View(model);
      }
   }
}

ASPLearning/Views/Shared/_Header.cshtml
@{
   Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <link href="~/Content/css/style.css" rel="stylesheet" />
    <link href="~/Content/css/home.css" rel="stylesheet" />
   <link href="~/Content/css/signin-signup.css" rel="stylesheet" />
   <link href="~/Content/CustomStyle.css" rel="stylesheet" />
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/v4-shims.css">
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <title>@ViewBag.Title</title>
</head>

<body>
   <nav class="navbar navbar-expand-sm navbar-light bg-light">
      <img src="@Url.Content("~/Content/picture/logo.png")" alt="" width="70px">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
               <a class="nav-link" href="/"><b>Study Online</b><span class="sr-only">(current)</span></a>
            </li>
         </ul>
         <!--<div id="my-shopping-card">
            <a href="/Search">
               <i class="fa fa-search fa-2x" aria-hidden="true"></i>
            </a>
         </div>-->
         @if (!HttpContext.Current.Request.Url.AbsolutePath.ToLower().StartsWith("/search"))
         {
            using (Html.BeginForm("Index", "Search", FormMethod.Post))
            {
               <div class="input-group">
                  <div class="input-group-prepend">
                     <select data-trigger="" name="search_type">
                        <option value="-1">All</option>
                        <option value="1">Course</option>
                        <option value="2">Category</option>
                        <option value="3">Teacher</option>
                     </select>
                  </div>
                  <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="search_value">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
               </div>
            }
         }
         &nbsp;
         @if (Session["username"] == null)
         {
            <button class="my-btn" onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Sign In</button>
            <button class="my-btn" onclick="location.href='/Login';" style="width:auto;">Sign Up</button>
         }
         else
         {
            <div class="dropdown">
               <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  @Session["username"]
               </button>
               <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="/Dashboard">Dashboard</a>
                  <a class="dropdown-item" href="/Dashboard#mycourse">My Course</a>
                  @if (Convert.ToInt32(Session["usertype"]) == 2)
                  {
                     <div class="dropdown-divider"></div>
                     <div class="dropdown-header">Management</div>
                     <a class="dropdown-item" href="/Dashboard#courses">Courses</a>
                     <a class="dropdown-item" href="/Dashboard#videos">Videos</a>
                  }
                  @if (Convert.ToInt32(Session["usertype"]) == 0)
                  {
                     <div class="dropdown-divider"></div>
                     <div class="dropdown-header">Administrator</div>
                     <a class="dropdown-item" href="/Management">Management</a>
                  }
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/Login/Logout">Logout</a>
               </div>
            </div>
         }
      </div>
   </nav>
   <!-- body -->
   @RenderBody()

   <div class="footer" style="color:#fff" >
       <!-- Footer -->
       <footer class="page-footer font-small mdb-color lighten-3 pt-4" style="background:#62627B">

           <!-- Footer Links -->
           <div class="container text-center text-md-left">

               <!-- Grid row -->
               <div class="row">

                   <!-- Grid column -->
                   <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1">

                       <!-- Content -->
                       <h5 class="font-weight-bold text-uppercase mb-4">Footer Content</h5>
                       <p>Here you can use rows and columns to organize your footer content.</p>
                       <p>
                           Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit amet numquam iure provident voluptate
                           esse
                           quasi, veritatis totam voluptas nostrum.
                       </p>

                   </div>
                   <!-- Grid column -->

                   <hr class="clearfix w-100 d-md-none">

                   <!-- Grid column -->
                   <div class="col-md-2 col-lg-2 mx-auto my-md-4 my-0 mt-4 mb-1">

                       <!-- Links -->
                       <h5 class="font-weight-bold text-uppercase mb-4">About</h5>

                       <ul class="list-unstyled">
                           <li>
                               <p>
                                  PROJECTS
                               </p>
                           </li>
                           <li>
                               <p>
                                   ABOUT US
                               </p>
                           </li>
                           <li>
                               <p>
                                  BLOG
                               </p>
                           </li>
                           <li>
                               <p>
                                   AWARDS
                               </p>
                           </li>
                       </ul>

                   </div>
                   <!-- Grid column -->

                   <hr class="clearfix w-100 d-md-none">

                   <!-- Grid column -->
                   <div class="col-md-4 col-lg-3 mx-auto my-md-4 my-0 mt-4 mb-1">

                       <!-- Contact details -->
                       <h5 class="font-weight-bold text-uppercase mb-4">Address</h5>

                       <ul class="list-unstyled">
                           <li>
                               <p>
                                   <i class="fas fa-home mr-3"></i> Trường Khoa học tự nhiên
                               </p>
                           </li>
                           <li>
                               <p>
                                   <i class="fas fa-envelope mr-3"></i> cnpm23@gmail.com
                               </p>
                           </li>
                           <li>
                               <p>
                                   <i class="fas fa-phone mr-3"></i> + 01 234 567 88
                               </p>
                           </li>
                           <li>
                               <p>
                                   <i class="fas fa-print mr-3"></i> + 01 234 567 89
                               </p>
                           </li>
                       </ul>

                   </div>
                   <!-- Grid column -->

                   <hr class="clearfix w-100 d-md-none">

                   <!-- Grid column -->
                   <div class="col-md-2 col-lg-2 text-center mx-auto my-4">

                       <!-- Social buttons -->
                       <h5 class="font-weight-bold text-uppercase mb-4">Follow Us</h5>

                       <!-- Facebook -->
                       <a type="button" class="btn-floating btn-fb">
                           <i class="fab fa-facebook-f"></i>
                       </a>
                       <!-- Twitter -->
                       <a type="button" class="btn-floating btn-tw">
                           <i class="fab fa-twitter"></i>
                       </a>
                       <!-- Google +-->
                       <a type="button" class="btn-floating btn-gplus">
                           <i class="fab fa-google-plus-g"></i>
                       </a>
                       <!-- Dribbble -->
                       <a type="button" class="btn-floating btn-dribbble">
                           <i class="fab fa-dribbble"></i>
                       </a>

                   </div>
                   <!-- Grid column -->

               </div>
               <!-- Grid row -->

           </div>
           <div class="footer-copyright text-center py-3" style="background:#585867">
               Group 23 - CQ2017/33

           </div>


       </footer>
       <!-- Footer -->
    </div>


   <!-- SIGN IN FORM -->
   @using (Html.BeginForm("AuthorizeMain", "Login", FormMethod.Post))
   {
      <div id="id01" class="modal">
         <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>

         <form class="modal-content">
            <div class="container">
               <h1>Sign In</h1>
               <p>Please fill in this form to login.</p>
               <hr>
               <label for="username"><b>Username</b></label>
               <input class="login" type="text" placeholder="Enter Username" name="username" required>

               <label for="pwd"><b>Password</b></label>
               <input class="login" type="password" placeholder="Enter Password" name="pwd" required>

               <label>
                  <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
               </label>

               <div id="btn-signup" class="clearfix">
                  <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
                  <button type="submit" class="signupbtn" name="login">Sign In</button>
               </div>
            </div>
         </form>
      </div>
      <script>
         // Get the modal
         var modal = document.getElementById('id01');

         // When the user clicks anywhere outside of the modal, close it
         window.onclick = function (event) {
            if (event.target == modal) {
               modal.style.display = "none";
            }
         }
      </script>
   }
   <!-- Compiled and minified JavaScript -->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   <script>
      $(document).ready(function () {
         $('body').bootstrapMaterialDesign();
      });
   </script>
   <script data-search-pseudo-elements defer src="https://use.fontawesome.com/releases/v5.12.0/js/all.js" integrity="sha384-L469/ELG4Bg9sDQbl0hvjMq8pOcqFgkSpwhwnslzvVVGpDjYJ6wJJyYjvG3u8XW7" crossorigin="anonymous"></script>
   <script src="https://kit.fontawesome.com/96c5b97f73.js" crossorigin="anonymous"></script>
</body>

</html>

ASPLearning/Views/Shared/_Layout.cshtml
@{
   Layout = "~/Views/Shared/_Header.cshtml";
}
@RenderSection("Slider", false)
<!-- content -->
<div class="main-content" style="min-width:400px">
   @RenderBody()
</div>
@if (Session["username"] != null)
{
   <!-- MAIN RIGHT CONTAINT MENU -->
   <div class="main-right">
      <ul class="list-group mt-5 d-none d-lg-block">
         <li class="list-group-item active">MENU</li>
         <li class="list-group-item"><a href="/Dashboard">Profile</a></li>
         <li class="list-group-item"><a href="/Dashboard#mycourse">My courses</a></li>
         @if (Convert.ToInt32(Session["usertype"]) == 2)
         {
            <li><a class="list-group-item" href="/Dashboard#courses">Posted Courses</a></li>
            <li><a class="list-group-item" href="/Dashboard#videos">Videos</a></li>
         }
         @if (Convert.ToInt32(Session["usertype"]) == 0)
         {
            <li><a class="list-group-item" href="/Management">Management</a></li>
         }
      </ul>
   </div>
}